config {
    type: "table",
    description: "Table of region and related country information in the AfQTS service. Each row is a unique region ID",
    assertions: {
        uniqueKey: ["region_id"],
    },
    columns: {
        region_id: "Unique identifier of the region",
        region_name: "Name of the region",
        country_id: "Country of this region",
        country_name: "Name of the country of this region",
        country_code: "Country code for the country of this region",
        regions_requires_preliminary_check: "TRUE if this region requires preliminary checks",
        regions_reduced_evidence_accepted: "TRUE if this reduced evidence is accepted for this region",
        teaching_authority_online_checker_url: "URL of the teaching authority",
        regions_teaching_authority_provides_written_statement: "TRUE if teacher authority provides a written statement",
        teaching_authority_requires_submission_email: "TRUE if teaching authority requires a submission email",
        regions_written_statement_optional: "TRUE if the written statement is optional",
        eligibility_enabled: "TRUE if eligibility is enabled",
        eligibility_skip_questions: "TRUE if eligibility skips questions",
        subject_limited: "TRUE if subject is limited",
        country_route: "Categorised area that this region is part of e.g. eea, eu, ott",
        country_eea: "TRUE if this region is part of the European Economic Area (EEA)",
        country_eu: "TRUE if this region is part of the European Union (EU)"
    }
}

SELECT
  regions.id AS region_id,
  regions.name AS region_name,
  countries.id AS country_id,
  country_codes.code as country_code,
  country_codes.country_name,
  regions_requires_preliminary_check,
  regions_reduced_evidence_accepted,
  teaching_authority_online_checker_url,
  regions_teaching_authority_provides_written_statement,
  teaching_authority_requires_submission_email,
  regions_written_statement_optional,
  eligibility_enabled,
  eligibility_skip_questions,
  subject_limited,
  ${countries.mapping("country_codes.country_name")} AS country_route,
  ${countries.mapping("country_codes.country_name")} = 'eea' AS country_eea,
  ${countries.mapping("country_codes.country_name")} IN ('eea', 'eu') AS country_eu,
FROM
  ${ref("regions_latest_afqts")} AS regions
INNER JOIN
  ${ref("countries_latest_afqts")} AS countries
ON
  regions.country_id = countries.id
INNER JOIN
  ${ref("country_codes")} AS country_codes
ON
  countries.code = country_codes.code
