config {
    type: "table"
}

SELECT
  reference,
  state,
  stage,
  statuses,
  action_required_by,
  assessor_id,
  application_forms.region_id,
  country_name,
  country_eea,
  MIN(valid_from) AS actioned_on
FROM
  ${ref("application_forms_version_afqts")} AS application_forms
LEFT JOIN
  ${ref("afqts_regions")} AS afqts_regions
ON
  application_forms.region_id = afqts_regions.region_id
WHERE
  state != "draft"
  OR stage != 'draft'
GROUP BY
  reference,
  state,
  stage,
  statuses,
  action_required_by,
  assessor_id,
  application_forms.region_id,
  country_name,
  country_eea
