config {
    type: "table"
}

SELECT
  * EXCEPT (region_id,
    country_name,
    country_code,
    country_id),
  afqts_regions.region_name AS region,
  CASE
    WHEN eligibility_checks.eligible_work_experience_in_england = TRUE THEN 'Selected Yes'
    WHEN eligibility_checks.eligible_work_experience_in_england = FALSE THEN 'Selected No'
    ELSE 'No Eligible work experience in England data present'
    END
    AS eligible_work_experience_in_england_reporting,
  CASE
    WHEN afqts_regions.country_name IS NOT NULL THEN afqts_regions.country_name
    ELSE 'No country data present'
    END
    AS country_name_reporting,
  CASE
    WHEN afqts_regions.country_eea = TRUE THEN 'EEA Country'
    WHEN afqts_regions.country_eea = FALSE THEN 'Non EEA Country'
    ELSE 'No EEA data present'
    END
    AS country_eea_reporting,
  CASE
    WHEN afqts_regions.country_eu = TRUE THEN 'EU Country'
    WHEN afqts_regions.country_eu = FALSE THEN 'Non EU Country'
    ELSE 'No EU data present'
    END
    AS country_eu_reporting,
FROM
  ${ref("eligibility_checks_latest_afqts")} AS eligibility_checks
LEFT JOIN
  ${ref("afqts_regions")} AS afqts_regions
ON
  eligibility_checks.region_id = afqts_regions.region_id
